### ISSUE TITLE
PolEval Template - metadata should be inside 'document'

### ISSUE THREAD

**Issue by adamjankaczmarek** [filipggg/paper-cutter#1]
https://github.com/filipggg/paper-cutter/blob/bdd9ac7b59c4e527650f878ce85c0a99b5beff7e/%7B%7Bcookiecutter.paper_repo_name%7D%7D/_latex-templates/poleval-template.tex#L17

`\input{metadata}` should be after `\begin{document}`  for properly rendering paper title and authors. Otherwise there would be overflow on the first page - space taken by so-called 'metadata' from before `\begin{document}' is not accounted for.

**Comment by adamjankaczmarek** [comment]
And https://github.com/filipggg/paper-cutter/blob/bdd9ac7b59c4e527650f878ce85c0a99b5beff7e/%7B%7Bcookiecutter.paper_repo_name%7D%7D/_latex-templates/poleval-template.tex#L35 should probably be moved to `main.tex`

**Comment by filipggg** [comment]
> https://github.com/filipggg/paper-cutter/blob/bdd9ac7b59c4e527650f878ce85c0a99b5beff7e/%7B%7Bcookiecutter.paper_repo_name%7D%7D/_latex-templates/poleval-template.tex#L17
> 
> `\input{metadata}` should be after `\begin{document}` for properly rendering paper title and authors. Otherwise there would be overflow on the first page - space taken by so-called 'metadata' from before `\begin{document}' is not accounted for.

I think you're right, though I simply copied it from the original template. I'll get in touch with the authors of the PolEval template and let you know.

**Comment by filipggg** [comment]
@adamjankaczmarek Thanks you pointing this out, fixed.
